name: QualityControl
'on':
  pull_request:
    branches:
    - main
jobs:
  quality-control:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setupconda
    - name: Install NB-Clean
      run: 'pip install nb-clean==2.0.2

        '
    - name: Ensure clean notebooks
      run: 'python .github/workflows/ensure_clean_notebooks.py

        '
    - name: Spellcheck
      if: always()
      uses: codespell-project/actions-codespell@master
      with:
        check_filenames: true
        check_hidden: true
        skip: '*.js,qaqc.yml'
        ignore_words_list: slippy,trough,thw
    - name: Disable Notebook Execution Before Linkcheck
      if: always()
      shell: python
      run: "import yaml\nwith open('./book/_config.yml') as f:\n  data = yaml.safe_load(f)\n\
        \  data['execute']['execute_notebooks'] = 'off'\nwith open('./book/_config.yml',\
        \ 'w') as f:\n  yaml.dump(data, f)\n"
    - name: Check External Links
      continue-on-error: true
      timeout-minutes: 5
      if: always()
      run: 'jb build book --builder linkcheck

        '
